<?xml version="1.0"?>
<robot>

  <property name="ground_clearance" value="0.125" />
  <property name="wheel_offset_x" value="0.05" />
  <property name="wheel_offset_y" value="0.143" />
  <property name="wheel_length" value="0.035" />
  <property name="wheel_radius" value="0.073" />
  <property name="base_size_x" value="0.31" />
  <property name="base_size_y" value="0.23" />
  <property name="base_size_z" value="0.078" />

  <!-- define a drive wheel -->
  <macro name="drive_wheel" params="suffix parent reflect color">
    <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 0 1" />
      <origin xyz="${wheel_offset_x} ${reflect*wheel_offset_y} ${wheel_radius}" rpy="${reflect*1.57} 0 0" />
      <parent link="${parent}_link"/>
      <child link="${parent}_${suffix}_wheel_link"/>
    </joint>
    <link name="${parent}_${suffix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="${color}" />
      </visual>
    </link>
  </macro>

  <!-- The xacro macro robot_base contains: base and wheels -->
  <macro name="robot_base" params="name color">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 ${ground_clearance}" rpy="0 0 0" />
        <geometry>
          <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
        </geometry>
        <material name="Grey" />
      </visual>
      <collision>
        <origin xyz="-${wheel_offset_x} 0 ${base_size_z/2}" rpy="0 0 0" />
        <geometry>
          <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
        </geometry>
      </collision>
    </link>
   
    <!-- drive wheels -->
    <drive_wheel parent="${name}" suffix="l" reflect="1" color="${color}"/>
    <drive_wheel parent="${name}" suffix="r" reflect="-1" color="${color}"/>
  </macro>

</robot>